// ai-agent-frontend/src/app/shared/layout/layout.component.ts
import { Component, signal } from '@angular/core';
import { Router, RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { NgClass, NgFor, NgIf } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';

interface NavItem {
  path: string;
  icon: string;
  label: string;
}

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, NgClass, NgFor, NgIf],
  template: `
    <div class="layout">
      <button class="sidebar-toggle" (click)="sidebarOpen.set(!sidebarOpen())" aria-label="Toggle menu">
        <span class="material-icons">{{ sidebarOpen() ? 'close' : 'menu' }}</span>
      </button>

      <div class="sidebar-overlay" *ngIf="sidebarOpen()" (click)="sidebarOpen.set(false)"></div>

      <div class="sidebar" [ngClass]="{'open': sidebarOpen()}">
        <div class="sidebar-header">
          <h2>AI Agent</h2>
        </div>

        <nav class="sidebar-nav">
          <a *ngFor="let item of navItems"
             [routerLink]="item.path"
             routerLinkActive="active"
             [routerLinkActiveOptions]="{exact: true}"
             class="nav-item"
             (click)="sidebarOpen.set(false)">
            <span class="material-icons">{{ item.icon }}</span>
            <span>{{ item.label }}</span>
          </a>
        </nav>

        <div class="sidebar-footer">
          <div class="user-info">
            <div class="user-avatar">{{ (auth.user()?.name || 'U').charAt(0) }}</div>
            <div class="user-details">
              <div class="user-name">{{ auth.user()?.name || 'User' }}</div>
              <div class="user-email">{{ auth.user()?.email || '' }}</div>
            </div>
          </div>
          <button class="logout-btn" (click)="handleLogout()">
            <span class="material-icons">logout</span>
            <span>Logout</span>
          </button>
        </div>
      </div>

      <div class="main-content">
        <router-outlet></router-outlet>
      </div>
    </div>
  `,
  styleUrl: './layout.component.scss'
})
export class LayoutComponent {
  sidebarOpen = signal(false);

  navItems: NavItem[] = [
    { path: '/dashboard', icon: 'home', label: 'Dashboard' },
    { path: '/tasks', icon: 'checklist', label: 'Tasks' },
    { path: '/calendar', icon: 'calendar_today', label: 'Calendar' },
    { path: '/messages', icon: 'chat', label: 'Messages' },
    { path: '/integrations', icon: 'settings', label: 'Integrations' },
    { path: '/settings', icon: 'manage_accounts', label: 'Settings' },
  ];

  constructor(
    public auth: AuthService,
    private router: Router
  ) {}

  handleLogout(): void {
    this.auth.logout();
  }
}

// ai-agent-frontend/src/components/Layout.jsx
// src/components/Layout.jsx
import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { 
  Home, 
  CheckSquare, 
  Calendar, 
  MessageCircle, 
  Settings, 
  LogOut,
  Menu,
  X
} from 'lucide-react';

export default function Layout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const { user, logout } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const navItems = [
    { path: '/', icon: Home, label: 'Dashboard' },
    { path: '/tasks', icon: CheckSquare, label: 'Tasks' },
    { path: '/calendar', icon: Calendar, label: 'Calendar' },
    { path: '/messages', icon: MessageCircle, label: 'Messages' },
    { path: '/integrations', icon: Settings, label: 'Integrations' },
  ];

  return (
    <div className="layout">
      {/* Mobile Sidebar Toggle */}
      <button 
        className="sidebar-toggle"
        onClick={() => setSidebarOpen(!sidebarOpen)}
      >
        {sidebarOpen ? <X size={24} /> : <Menu size={24} />}
      </button>

      {/* Sidebar */}
      <div className={`sidebar ${sidebarOpen ? 'open' : ''}`}>
        <div className="sidebar-header">
          <h2>AI Agent</h2>
        </div>
        
        <nav className="sidebar-nav">
          {navItems.map((item) => {
            const Icon = item.icon;
            const isActive = location.pathname === item.path;
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`nav-item ${isActive ? 'active' : ''}`}
                onClick={() => setSidebarOpen(false)}
              >
                <Icon size={20} />
                <span>{item.label}</span>
              </Link>
            );
          })}
        </nav>

        <div className="sidebar-footer">
          <div className="user-info">
            <div className="user-avatar">
              {user?.name?.charAt(0) || 'U'}
            </div>
            <div className="user-details">
              <div className="user-name">{user?.name || 'User'}</div>
              <div className="user-email">{user?.email || ''}</div>
            </div>
          </div>
          <button onClick={handleLogout} className="logout-btn">
            <LogOut size={20} />
            <span>Logout</span>
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="main-content">
        {children}
      </div>
    </div>
  );
}
