// ai-agent-frontend/src/pages/Register.jsx
// src/pages/Register.jsx
import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useNavigate, Link } from 'react-router-dom';

export default function Register() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: ''
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [passwordStrength, setPasswordStrength] = useState({
    score: 0,
    feedback: []
  });
  
  const { register } = useAuth();
  const navigate = useNavigate();

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value
    });

    // Check password strength in real-time
    if (name === 'password') {
      checkPasswordStrength(value);
    }
  };

  const checkPasswordStrength = (password) => {
    let score = 0;
    const feedback = [];

    if (password.length >= 8) score += 1;
    else feedback.push('At least 8 characters');

    if (/[A-Z]/.test(password)) score += 1;
    else feedback.push('One uppercase letter');

    if (/[a-z]/.test(password)) score += 1;
    else feedback.push('One lowercase letter');

    if (/[0-9]/.test(password)) score += 1;
    else feedback.push('One number');

    if (/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(password)) score += 1;
    else feedback.push('One special character');

    setPasswordStrength({ score, feedback });
  };

  const getPasswordStrengthColor = () => {
    if (passwordStrength.score === 0) return '#e74c3c';
    if (passwordStrength.score <= 2) return '#e67e22';
    if (passwordStrength.score <= 4) return '#f1c40f';
    return '#2ecc71';
  };

  const getPasswordStrengthText = () => {
    if (passwordStrength.score === 0) return 'Very Weak';
    if (passwordStrength.score <= 2) return 'Weak';
    if (passwordStrength.score <= 4) return 'Good';
    return 'Strong';
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    // Client-side validation
    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match');
      setLoading(false);
      return;
    }

    if (passwordStrength.score < 3) {
      setError('Please choose a stronger password');
      setLoading(false);
      return;
    }

    try {
      const result = await register(formData.name, formData.email, formData.password);
      if (result.success) {
        navigate('/');
      } else {
        setError(result.error || 'Registration failed');
      }
    } catch (err) {
      setError('An error occurred during registration');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <div className="login-header">
          <h1>AI Agent</h1>
          <p>Create your account</p>
        </div>
        
        <form onSubmit={handleSubmit} className="login-form">
          {error && <div className="error-message">{error}</div>}
          
          <div className="form-group">
            <label htmlFor="name">Full Name</label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
              placeholder="Enter your full name"
              required
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="Enter your email"
              required
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="Enter your password"
              required
              minLength="6"
            />
            {formData.password && (
              <div className="password-strength">
                <div className="strength-bar">
                  <div 
                    className="strength-fill"
                    style={{
                      width: `${(passwordStrength.score / 5) * 100}%`,
                      backgroundColor: getPasswordStrengthColor()
                    }}
                  ></div>
                </div>
                <div className="strength-text">
                  Strength: <span style={{ color: getPasswordStrengthColor() }}>
                    {getPasswordStrengthText()}
                  </span>
                </div>
                {passwordStrength.feedback.length > 0 && (
                  <div className="password-feedback">
                    {passwordStrength.feedback.map((msg, index) => (
                      <div key={index} className="feedback-item">• {msg}</div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
          
          <div className="form-group">
            <label htmlFor="confirmPassword">Confirm Password</label>
            <input
              type="password"
              id="confirmPassword"
              name="confirmPassword"
              value={formData.confirmPassword}
              onChange={handleChange}
              placeholder="Confirm your password"
              required
              minLength="6"
            />
            {formData.confirmPassword && formData.password !== formData.confirmPassword && (
              <div className="error-text">Passwords do not match</div>
            )}
          </div>
          
          <button 
            type="submit" 
            className="login-btn"
            disabled={loading || formData.password !== formData.confirmPassword || passwordStrength.score < 3}
          >
            {loading ? 'Creating account...' : 'Sign up'}
          </button>
        </form>
        
        <div className="login-footer">
          <p>Already have an account? <Link to="/login">Sign in</Link></p>
        </div>
      </div>
    </div>
  );
}

// ai-agent-frontend/src/app/features/auth/register.component.ts
import { Component, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { NgIf, NgFor } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [FormsModule, RouterLink, NgIf, NgFor],
  template: `
    <div class="auth-container">
      <div class="auth-card">
        <div class="auth-header">
          <h1>AI Agent</h1>
          <p>Create your account</p>
        </div>

        <form (ngSubmit)="handleSubmit()" class="auth-form">
          <div class="error-message" *ngIf="error()">{{ error() }}</div>

          <div class="form-group">
            <label for="name">Full Name</label>
            <input type="text" id="name" [(ngModel)]="name" name="name" placeholder="Enter your full name" required />
          </div>

          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" id="email" [(ngModel)]="email" name="email" placeholder="Enter your email" required />
          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" [(ngModel)]="password" name="password" placeholder="Enter your password" required (input)="checkPasswordStrength(password)" />
            <div class="password-strength" *ngIf="password">
              <div class="strength-bar">
                <div class="strength-fill" [style.width.%]="(strengthScore()/5)*100" [style.background-color]="strengthColor()"></div>
              </div>
              <div class="strength-text">Strength: <span [style.color]="strengthColor()">{{ strengthText() }}</span></div>
              <div class="password-feedback" *ngIf="feedback().length">
                <div *ngFor="let msg of feedback()" class="feedback-item">&bull; {{ msg }}</div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="confirmPassword">Confirm Password</label>
            <input type="password" id="confirmPassword" [(ngModel)]="confirmPassword" name="confirmPassword" placeholder="Confirm your password" required />
            <div class="error-text" *ngIf="confirmPassword && password !== confirmPassword">Passwords do not match</div>
          </div>

          <button type="submit" class="auth-btn" [disabled]="loading() || password !== confirmPassword || strengthScore() < 3">
            {{ loading() ? 'Creating account...' : 'Sign up' }}
          </button>
        </form>

        <div class="auth-footer">
          <p>Already have an account? <a routerLink="/login">Sign in</a></p>
        </div>
      </div>
    </div>
  `,
  styleUrl: './auth.component.scss'
})
export class RegisterComponent {
  name = '';
  email = '';
  password = '';
  confirmPassword = '';
  loading = signal(false);
  error = signal('');

  strengthScore = signal(0);
  feedback = signal<string[]>([]);

  constructor(
    private auth: AuthService,
    private router: Router
  ) {}

  strengthColor(): string {
    const s = this.strengthScore();
    if (s === 0) return '#e74c3c';
    if (s <= 2) return '#e67e22';
    if (s <= 4) return '#f1c40f';
    return '#2ecc71';
  }

  strengthText(): string {
    const s = this.strengthScore();
    if (s === 0) return 'Very Weak';
    if (s <= 2) return 'Weak';
    if (s <= 4) return 'Good';
    return 'Strong';
  }

  checkPasswordStrength(pw: string): void {
    let score = 0;
    const fb: string[] = [];
    if (pw.length >= 8) score++; else fb.push('At least 8 characters');
    if (/[A-Z]/.test(pw)) score++; else fb.push('One uppercase letter');
    if (/[a-z]/.test(pw)) score++; else fb.push('One lowercase letter');
    if (/[0-9]/.test(pw)) score++; else fb.push('One number');
    if (/[!@#$%^&*()_+=\-\[\]{};':"\\|,.<>\/?]/.test(pw)) score++; else fb.push('One special character');
    this.strengthScore.set(score);
    this.feedback.set(fb);
  }

  async handleSubmit(): Promise<void> {
    if (!this.name || !this.email || !this.password) return;
    if (this.password !== this.confirmPassword) { this.error.set('Passwords do not match'); return; }
    if (this.strengthScore() < 3) { this.error.set('Please choose a stronger password'); return; }

    this.loading.set(true);
    this.error.set('');

    const success = await this.auth.register({ name: this.name, email: this.email, password: this.password });
    if (success) {
      this.router.navigate(['/dashboard']);
    } else {
      this.error.set('Registration failed. Please try again.');
    }
    this.loading.set(false);
  }
}
