// ai-agent-frontend/src/pages/Messages.jsx
// src/pages/Messages.jsx
import React, { useState, useEffect, useRef } from 'react';
import { Send, Bot, User } from 'lucide-react';
import { messageService } from '../services/api';

export default function Messages() {
  const [messages, setMessages] = useState([]);
  const [newMessage, setNewMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const sendMessage = async (e) => {
    e.preventDefault();
    if (!newMessage.trim()) return;

    const userMessage = { text: newMessage, sender: 'user', timestamp: new Date() };
    setMessages(prev => [...prev, userMessage]);
    setNewMessage('');
    setLoading(true);

    try {
      const response = await messageService.send(newMessage);
      const botMessage = { 
        text: response.result || response.message || 'I received your message!', 
        sender: 'bot', 
        timestamp: new Date() 
      };
      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      const errorMessage = { 
        text: 'Sorry, I encountered an error. Please try again.', 
        sender: 'bot', 
        timestamp: new Date() 
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setLoading(false);
    }
  };

  const quickCommands = [
    'Schedule meeting tomorrow at 3 PM',
    'Create task for project report',
    'Show my calendar',
    'Check my emails'
  ];

  return (
    <div className="messages-page">
      <div className="page-header">
        <div className="header-content">
          <h1>AI Assistant</h1>
          <p>Chat with your AI assistant</p>
        </div>
      </div>

      <div className="chat-container">
        <div className="chat-messages">
          {messages.length === 0 ? (
            <div className="welcome-message">
              <Bot size={48} />
              <h3>Hello! I'm your AI Assistant</h3>
              <p>I can help you with:</p>
              <ul>
                <li>📅 Scheduling meetings and events</li>
                <li>✅ Creating and managing tasks</li>
                <li>🔔 Setting reminders</li>
                <li>📧 Checking and sending emails</li>
              </ul>
              <p>Try one of these commands or ask me anything!</p>
              
              <div className="quick-commands">
                {quickCommands.map((command, index) => (
                  <button
                    key={index}
                    className="quick-command"
                    onClick={() => setNewMessage(command)}
                  >
                    {command}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            messages.map((message, index) => (
              <div key={index} className={`message ${message.sender}`}>
                <div className="message-avatar">
                  {message.sender === 'bot' ? <Bot size={20} /> : <User size={20} />}
                </div>
                <div className="message-content">
                  <div className="message-text">{message.text}</div>
                  <div className="message-time">
                    {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </div>
                </div>
              </div>
            ))
          )}
          {loading && (
            <div className="message bot">
              <div className="message-avatar">
                <Bot size={20} />
              </div>
              <div className="message-content">
                <div className="typing-indicator">
                  <span></span>
                  <span></span>
                  <span></span>
                </div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        <form onSubmit={sendMessage} className="chat-input">
          <input
            type="text"
            value={newMessage}
            onChange={(e) => setNewMessage(e.target.value)}
            placeholder="Type your message..."
            disabled={loading}
          />
          <button type="submit" disabled={loading || !newMessage.trim()}>
            <Send size={20} />
          </button>
        </form>
      </div>
    </div>
  );
}

// ai-agent-frontend/src/app/features/messages/messages.component.ts
import { Component, OnInit, signal, ElementRef, ViewChild, AfterViewChecked, OnDestroy } from '@angular/core';
import { NgIf, NgFor, NgClass, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../shared/toast/toast.service';

interface ChatDisplay {
  text: string;
  sender: 'user' | 'bot';
  timestamp: Date;
}

@Component({
  selector: 'app-messages',
  standalone: true,
  imports: [NgIf, NgFor, NgClass, DatePipe, FormsModule],
  template: `
    <div class="messages-page">
      <div class="page-header">
        <div class="header-content">
          <h1>AI Assistant</h1>
          <p>Chat with your AI assistant</p>
        </div>
        <button *ngIf="messages().length > 0" class="btn btn-secondary" (click)="clearHistory()">
          <span class="material-icons">delete_sweep</span> Clear Chat
        </button>
      </div>

      <div class="chat-container">
        <div class="chat-messages" #messagesContainer>
          <div *ngIf="messages().length === 0" class="welcome-message">
            <span class="material-icons" style="font-size:48px">smart_toy</span>
            <h3>Hello! I'm your AI Assistant</h3>
            <p>I can help you with:</p>
            <ul>
              <li>Scheduling meetings and events</li>
              <li>Creating and managing tasks</li>
              <li>Setting reminders</li>
              <li>Checking and sending emails</li>
            </ul>
            <p>Try one of these commands or ask me anything!</p>
            <div class="quick-commands">
              <button *ngFor="let cmd of quickCommands" class="quick-command" (click)="newMessage.set(cmd)">{{ cmd }}</button>
            </div>
          </div>

          <div *ngFor="let msg of messages(); let i = index" class="message" [ngClass]="msg.sender">
            <div class="message-avatar">
              <span class="material-icons">{{ msg.sender === 'bot' ? 'smart_toy' : 'person' }}</span>
            </div>
            <div class="message-content">
              <div class="message-text">{{ msg.text }}</div>
              <div class="message-time">{{ msg.timestamp | date:'shortTime' }}</div>
            </div>
          </div>

          <div *ngIf="loading()" class="message bot">
            <div class="message-avatar"><span class="material-icons">smart_toy</span></div>
            <div class="message-content">
              <div class="typing-indicator"><span></span><span></span><span></span></div>
            </div>
          </div>
          <div #scrollTarget></div>
        </div>

        <form (ngSubmit)="sendMessage()" class="chat-input">
          <input type="text" [(ngModel)]="newMessage" name="message" placeholder="Type your message..." [disabled]="loading()" />
          <button type="submit" [disabled]="loading() || !newMessage().trim()">
            <span class="material-icons">send</span>
          </button>
        </form>
      </div>
    </div>
  `,
  styleUrl: './messages.component.scss'
})
export class MessagesComponent implements OnInit, AfterViewChecked, OnDestroy {
  @ViewChild('scrollTarget') scrollTarget!: ElementRef;
  @ViewChild('messagesContainer') messagesContainer!: ElementRef;

  messages = signal<ChatDisplay[]>([]);
  newMessage = signal('');
  loading = signal(false);
  private subs: Subscription[] = [];

  quickCommands = [
    'Schedule meeting tomorrow at 3 PM',
    'Create task for project report',
    'Show my calendar',
    'Check my emails'
  ];

  constructor(
    private api: ApiService,
    private toast: ToastService
  ) {}

  ngOnInit(): void { this.loadHistory(); }
  ngOnDestroy(): void { this.subs.forEach(s => s.unsubscribe()); }

  ngAfterViewChecked(): void { this.scrollToBottom(); }

  private scrollToBottom(): void {
    try { this.scrollTarget?.nativeElement?.scrollIntoView({ behavior: 'smooth' }); } catch {}
  }

  loadHistory(): void {
    this.subs.push(this.api.getChatHistory().subscribe(msgs => {
      this.messages.set(msgs.map(m => ({
        text: m.text,
        sender: m.role === 'assistant' ? 'bot' : 'user',
        timestamp: new Date(m.createdAt)
      })));
    }));
  }

  sendMessage(): void {
    const text = this.newMessage().trim();
    if (!text) return;

    this.messages.update(msgs => [...msgs, { text, sender: 'user', timestamp: new Date() }]);
    this.newMessage.set('');
    this.loading.set(true);

    this.subs.push(this.api.sendMessage(text).subscribe({
      next: (res) => {
        this.messages.update(msgs => [...msgs, { text: res.result || 'I received your message!', sender: 'bot', timestamp: new Date() }]);
        this.loading.set(false);
      },
      error: () => {
        this.messages.update(msgs => [...msgs, { text: 'Sorry, I encountered an error. Please try again.', sender: 'bot', timestamp: new Date() }]);
        this.loading.set(false);
      }
    }));
  }

  clearHistory(): void {
    this.subs.push(this.api.clearChatHistory().subscribe(() => {
      this.messages.set([]);
      this.toast.success('Chat history cleared');
    }));
  }
}
