// ai-agent-frontend/src/pages/Dashboard.jsx
// src/pages/Dashboard.jsx
import React, { useState, useEffect } from 'react';
import { Calendar, CheckSquare, Mail, MessageCircle, TrendingUp } from 'lucide-react';
import { userService, taskService, eventService } from '../services/api';

export default function Dashboard() {
  const [stats, setStats] = useState({ 
    tasks: { total: 0, completed: 0, thisWeek: 0, thisMonth: 0 },
    events: { total: 0, upcoming: 0, thisWeek: 0, thisMonth: 0 }
  });
  const [recentTasks, setRecentTasks] = useState([]);
  const [todayEvents, setTodayEvents] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadDashboardData();
  }, []);

  const loadDashboardData = async () => {
    try {
      const [statsData, tasksData, eventsData] = await Promise.all([
        userService.getStats(),
        taskService.getAll(),
        eventService.getAll()
      ]);

      setStats(statsData);
      setRecentTasks(tasksData.slice(0, 5));
      
      const today = new Date().toDateString();
      const todayEventsData = eventsData.filter(event => 
        event.startUtc && new Date(event.startUtc).toDateString() === today
      ).slice(0, 5);
      setTodayEvents(todayEventsData);
    } catch (error) {
      console.error('Failed to load dashboard data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleTaskComplete = async (taskId) => {
    try {
      await taskService.complete(taskId);
      loadDashboardData();
    } catch (error) {
      console.error('Failed to complete task:', error);
    }
  };

  if (loading) {
    return <div className="loading">Loading dashboard...</div>;
  }

  return (
    <div className="dashboard">
      <div className="dashboard-header">
        <h1>Dashboard</h1>
        <p>Welcome back! Here's your productivity overview.</p>
      </div>

      {/* Stats Cards */}
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon" style={{background: 'var(--primary-gradient)'}}>
            <CheckSquare size={24} />
          </div>
          <div className="stat-content">
            <h3>{stats.tasks.total || 0}</h3>
            <p>Total Tasks</p>
            <div className="stat-details">
              <span className="completed">{stats.tasks.completed || 0} done</span>
              <span className="in-progress">{stats.tasks.thisWeek || 0} this week</span>
            </div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{background: 'var(--secondary-gradient)'}}>
            <Calendar size={24} />
          </div>
          <div className="stat-content">
            <h3>{stats.events.total || 0}</h3>
            <p>Total Events</p>
            <div className="stat-details">
              <span className="upcoming">{stats.events.upcoming || 0} upcoming</span>
              <span className="this-week">{stats.events.thisWeek || 0} this week</span>
            </div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{background: 'var(--accent-gradient)'}}>
            <Mail size={24} />
          </div>
          <div className="stat-content">
            <h3>✓</h3>
            <p>Gmail Connected</p>
            <div className="stat-details">
              <span className="synced">Auto-syncing</span>
            </div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{background: 'var(--success-gradient)'}}>
            <TrendingUp size={24} />
          </div>
          <div className="stat-content">
            <h3>{stats.tasks.total > 0 ? Math.round((stats.tasks.completed / stats.tasks.total) * 100) : 0}%</h3>
            <p>Completion Rate</p>
            <div className="stat-details">
              <span className="positive">Keep going!</span>
            </div>
          </div>
        </div>
      </div>

      {/* Recent Tasks & Events */}
      <div className="dashboard-content">
        <div className="content-column">
          <div className="content-card">
            <h3>Recent Tasks</h3>
            <div className="task-list">
              {recentTasks.length === 0 ? (
                <p className="empty-state">No tasks found</p>
              ) : (
                recentTasks.map(task => (
                  <div key={task.id} className="task-item">
                    <div className="task-checkbox">
                      <input 
                        type="checkbox" 
                        checked={task.status === 'Done'} 
                        onChange={() => handleTaskComplete(task.id)}
                      />
                    </div>
                    <div className="task-content">
                      <div className={`task-title ${task.status === 'Done' ? 'completed' : ''}`}>
                        {task.title}
                      </div>
                      <div className="task-meta">
                        {task.dueUtc && <span className="due-date">Due: {new Date(task.dueUtc).toLocaleDateString()}</span>}
                        <span className={`status-badge ${task.status?.toLowerCase().replace(' ', '-')}`}>
                          {task.status}
                        </span>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        <div className="content-column">
          <div className="content-card">
            <h3>Today's Events</h3>
            <div className="event-list">
              {todayEvents.length === 0 ? (
                <p className="empty-state">No events today</p>
              ) : (
                todayEvents.map(event => (
                  <div key={event.id} className="event-item">
                    <div className="event-time">
                      {event.startUtc ? new Date(event.startUtc).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'All day'}
                    </div>
                    <div className="event-content">
                      <div className="event-title">{event.title}</div>
                      {event.location && <div className="event-location">{event.location}</div>}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Quick Actions */}
      <div className="quick-actions">
        <h3>Quick Actions</h3>
        <div className="action-buttons">
          <button className="action-btn" onClick={() => window.location.href = '/tasks'}>
            <CheckSquare size={20} /> Add Task
          </button>
          <button className="action-btn" onClick={() => window.location.href = '/calendar'}>
            <Calendar size={20} /> Schedule Event
          </button>
          <button className="action-btn" onClick={() => window.location.href = '/messages'}>
            <MessageCircle size={20} /> Chat with AI
          </button>
        </div>
      </div>
    </div>
  );
}

// ai-agent-frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, OnInit, signal, computed, effect, OnDestroy } from '@angular/core';
import { NgIf, NgFor, NgClass, DatePipe } from '@angular/common';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { SignalRService } from '../../core/services/signalr.service';
import { UserStats, TaskItem, CalendarEvent } from '../../core/models/models';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [NgIf, NgFor, NgClass, DatePipe],
  template: `
    <div class="dashboard">
      <div class="dashboard-header">
        <h1>Dashboard</h1>
        <p>Welcome back! Here's your productivity overview.</p>
      </div>

      <div *ngIf="loading()" class="loading-state">
        <div class="spinner"></div>
        <p>Loading dashboard...</p>
      </div>

      <ng-container *ngIf="!loading()">
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-icon" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%)">
              <span class="material-icons">checklist</span>
            </div>
            <div class="stat-content">
              <h3>{{ stats().tasks.total }}</h3>
              <p>Total Tasks</p>
              <div class="stat-details">
                <span class="completed">{{ stats().tasks.completed }} done</span>
                <span class="in-progress">{{ stats().tasks.thisWeek }} this week</span>
              </div>
            </div>
          </div>

          <div class="stat-card">
            <div class="stat-icon" style="background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)">
              <span class="material-icons">calendar_today</span>
            </div>
            <div class="stat-content">
              <h3>{{ stats().events.total }}</h3>
              <p>Total Events</p>
              <div class="stat-details">
                <span class="upcoming">{{ stats().events.upcoming }} upcoming</span>
                <span class="this-week">{{ stats().events.thisWeek }} this week</span>
              </div>
            </div>
          </div>

          <div class="stat-card">
            <div class="stat-icon" style="background: linear-gradient(135deg, #f5576c 0%, #ff7a5a 100%)">
              <span class="material-icons">mail</span>
            </div>
            <div class="stat-content">
              <h3 *ngIf="googleConnected()">&#10003;</h3>
              <h3 *ngIf="!googleConnected()">&#10007;</h3>
              <p>Gmail Connected</p>
              <div class="stat-details">
                <span class="synced" *ngIf="googleConnected()">Connected</span>
                <span class="disconnected" *ngIf="!googleConnected()">Not Connected</span>
              </div>
            </div>
          </div>

          <div class="stat-card">
            <div class="stat-icon" style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)">
              <span class="material-icons">trending_up</span>
            </div>
            <div class="stat-content">
              <h3>{{ completionRate() }}%</h3>
              <p>Completion Rate</p>
              <div class="stat-details">
                <span class="positive">Keep going!</span>
              </div>
            </div>
          </div>
        </div>

        <div class="dashboard-content">
          <div class="content-column">
            <div class="content-card">
              <h3>Recent Tasks</h3>
              <div class="task-list">
                <div *ngIf="recentTasks().length === 0" class="empty-state">No tasks found</div>
                <div *ngFor="let task of recentTasks()" class="task-item">
                  <div class="task-checkbox">
                    <input type="checkbox" [checked]="task.status === 'Done'" (change)="handleTaskComplete(task.id)" />
                  </div>
                  <div class="task-content">
                    <div class="task-title" [ngClass]="{'completed': task.status === 'Done'}">{{ task.title }}</div>
                    <div class="task-meta">
                      <span *ngIf="task.dueUtc" class="due-date">Due: {{ task.dueUtc | date:'mediumDate' }}</span>
                      <span class="status-badge to-do">{{ task.status }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="content-column">
            <div class="content-card">
              <h3>Today's Events</h3>
              <div class="event-list">
                <div *ngIf="todayEvents().length === 0" class="empty-state">No events today</div>
                <div *ngFor="let event of todayEvents()" class="event-item">
                  <div class="event-time">{{ event.startUtc | date:'shortTime' }}</div>
                  <div class="event-content">
                    <div class="event-title">{{ event.title }}</div>
                    <div *ngIf="event.location" class="event-location">{{ event.location }}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="quick-actions">
          <h3>Quick Actions</h3>
          <div class="action-buttons">
            <button class="action-btn" (click)="router.navigate(['/tasks'])" aria-label="Add task">
              <span class="material-icons">checklist</span> Add Task
            </button>
            <button class="action-btn" (click)="router.navigate(['/calendar'])" aria-label="Schedule event">
              <span class="material-icons">calendar_today</span> Schedule Event
            </button>
            <button class="action-btn" (click)="router.navigate(['/messages'])" aria-label="Chat with AI">
              <span class="material-icons">chat</span> Chat with AI
            </button>
          </div>
        </div>
      </ng-container>
    </div>
  `,
  styleUrl: './dashboard.component.scss'
})
export class DashboardComponent implements OnInit, OnDestroy {
  loading = signal(true);
  stats = signal<UserStats>({ tasks: { total: 0, completed: 0, thisWeek: 0, thisMonth: 0 }, events: { total: 0, upcoming: 0, thisWeek: 0, thisMonth: 0 } });
  recentTasks = signal<TaskItem[]>([]);
  todayEvents = signal<CalendarEvent[]>([]);
  googleConnected = signal(false);
  private subs: Subscription[] = [];

  completionRate = computed(() => {
    const s = this.stats();
    return s.tasks.total > 0 ? Math.round((s.tasks.completed / s.tasks.total) * 100) : 0;
  });

  constructor(
    public router: Router,
    private api: ApiService,
    private signalR: SignalRService
  ) {
    effect(() => {
      const n = this.signalR.notificationSignal();
      if (n) this.loadDashboardData();
    });
  }

  ngOnInit(): void { this.loadDashboardData(); }
  ngOnDestroy(): void { this.subs.forEach(s => s.unsubscribe()); }

  loadDashboardData(): void {
    this.subs.push(this.api.getStats().subscribe(stats => this.stats.set(stats)));
    this.subs.push(this.api.getTasks().subscribe(tasks => this.recentTasks.set(tasks.slice(0, 5))));
    this.subs.push(this.api.getEvents(new Date().toISOString()).subscribe(events => {
      const today = new Date().toDateString();
      this.todayEvents.set(events.filter(e => e.startUtc && new Date(e.startUtc).toDateString() === today).slice(0, 5));
    }));
    this.subs.push(this.api.getGoogleStatus().subscribe(s => this.googleConnected.set(s.connected)));
    this.loading.set(false);
  }

  handleTaskComplete(taskId: number): void {
    this.subs.push(this.api.completeTask(taskId).subscribe(() => this.loadDashboardData()));
  }
}
