// ai-agent-frontend/src/app/features/calendar/calendar.component.ts
import { Component, OnInit, signal, OnDestroy } from '@angular/core';
import { NgIf, NgFor, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { CalendarEvent } from '../../core/models/models';
import { ToastService } from '../../shared/toast/toast.service';

@Component({
  selector: 'app-calendar',
  standalone: true,
  imports: [NgIf, NgFor, DatePipe, FormsModule],
  template: `
    <div class="calendar-page">
      <div class="page-header">
        <div class="header-content">
          <h1>Calendar</h1>
          <p>Manage your events and schedule</p>
        </div>
        <button class="btn btn-primary" (click)="openNewEvent()">
          <span class="material-icons">add</span> New Event
        </button>
      </div>

      <div class="modal-overlay" *ngIf="showModal()" (click)="closeModal()">
        <div class="modal" (click)="$event.stopPropagation()">
          <h2>{{ editingEvent() ? 'Edit Event' : 'Create New Event' }}</h2>
          <form (ngSubmit)="editingEvent() ? updateEvent() : createEvent()">
            <div class="form-group"><label>Title *</label><input type="text" [(ngModel)]="form.title" name="title" required placeholder="Meeting with team" /></div>
            <div class="form-group"><label>Description</label><textarea [(ngModel)]="form.description" name="desc" rows="3" placeholder="Brief description..."></textarea></div>
            <div class="form-row">
              <div class="form-group"><label>Start *</label><input type="datetime-local" [(ngModel)]="form.startUtc" name="start" required /></div>
              <div class="form-group"><label>End *</label><input type="datetime-local" [(ngModel)]="form.endUtc" name="end" required /></div>
            </div>
            <div class="form-group"><label>Location</label><input type="text" [(ngModel)]="form.location" name="loc" placeholder="Conference Room A" /></div>
            <div class="form-group"><label>Attendees</label><input type="text" [(ngModel)]="form.attendeesCsv" name="att" placeholder="email1@example.com, email2@example.com" /><small>Separate multiple emails with commas</small></div>
            <div class="modal-actions">
              <button type="button" class="btn btn-secondary" (click)="closeModal()">Cancel</button>
              <button type="submit" class="btn btn-primary">{{ editingEvent() ? 'Update' : 'Create' }} Event</button>
            </div>
          </form>
        </div>
      </div>

      <div class="calendar-content">
        <div class="events-section">
          <h2>Upcoming Events ({{ upcomingEvents().length }})</h2>
          <div class="events-list">
            <div *ngIf="loading()" class="loading-state"><div class="spinner"></div><p>Loading events...</p></div>
            <div *ngIf="!loading() && upcomingEvents().length === 0" class="empty-state">
              <span class="material-icons" style="font-size:48px;color:#ccc">calendar_today</span>
              <p>No upcoming events</p>
              <button class="btn btn-primary" (click)="openNewEvent()">Schedule Your First Event</button>
            </div>
            <div *ngFor="let event of upcomingEvents()" class="event-card">
              <div class="event-time">
                <div class="event-date">{{ event.startUtc | date:'mediumDate' }}</div>
                <div class="event-time-display"><span class="material-icons" style="font-size:14px">schedule</span> {{ event.startUtc | date:'shortTime' }} - {{ event.endUtc | date:'shortTime' }}</div>
              </div>
              <div class="event-content">
                <h3>{{ event.title }}</h3>
                <p *ngIf="event.description" class="event-description">{{ event.description }}</p>
                <div class="event-details">
                  <div *ngIf="event.location" class="event-location"><span class="material-icons" style="font-size:14px">location_on</span> {{ event.location }}</div>
                </div>
              </div>
              <div class="event-actions">
                <span class="event-status">{{ event.status || 'Scheduled' }}</span>
                <button class="icon-btn" (click)="openEditEvent(event)" aria-label="Edit event"><span class="material-icons">edit</span></button>
                <button class="icon-btn" (click)="deleteEvent(event.id)" aria-label="Delete event"><span class="material-icons">delete</span></button>
              </div>
            </div>
          </div>
        </div>

        <div *ngIf="pastEvents().length > 0" class="events-section">
          <h2>Past Events ({{ pastEvents().length }})</h2>
          <div class="events-list">
            <div *ngFor="let event of pastEvents()" class="event-card past">
              <div class="event-time">
                <div class="event-date">{{ event.startUtc | date:'mediumDate' }}</div>
                <div class="event-time-display">{{ event.startUtc | date:'shortTime' }} - {{ event.endUtc | date:'shortTime' }}</div>
              </div>
              <div class="event-content">
                <h3>{{ event.title }}</h3>
                <p *ngIf="event.description" class="event-description">{{ event.description }}</p>
                <div *ngIf="event.location" class="event-location"><span class="material-icons" style="font-size:14px">location_on</span> {{ event.location }}</div>
              </div>
              <div class="event-actions"><span class="event-status completed">Completed</span></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrl: './calendar.component.scss'
})
export class CalendarComponent implements OnInit, OnDestroy {
  events = signal<CalendarEvent[]>([]);
  loading = signal(true);
  showModal = signal(false);
  editingEvent = signal<CalendarEvent | null>(null);

  form = { title: '', description: '', startUtc: '', endUtc: '', location: '', attendeesCsv: '' };
  private subs: Subscription[] = [];

  upcomingEvents = () => this.events().filter(e => new Date(e.startUtc) >= new Date()).sort((a, b) => new Date(a.startUtc).getTime() - new Date(b.startUtc).getTime());
  pastEvents = () => this.events().filter(e => new Date(e.startUtc) < new Date()).sort((a, b) => new Date(b.startUtc).getTime() - new Date(a.startUtc).getTime());

  constructor(
    private api: ApiService,
    private toast: ToastService
  ) {}

  ngOnInit(): void { this.loadEvents(); }
  ngOnDestroy(): void { this.subs.forEach(s => s.unsubscribe()); }

  loadEvents(): void {
    this.loading.set(true);
    const today = new Date().toISOString();
    const nextMonth = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();
    this.subs.push(this.api.getEvents(today, nextMonth).subscribe(events => {
      this.events.set(events);
      this.loading.set(false);
    }));
  }

  openNewEvent(): void {
    this.editingEvent.set(null);
    this.form = { title: '', description: '', startUtc: '', endUtc: '', location: '', attendeesCsv: '' };
    this.showModal.set(true);
  }

  openEditEvent(event: CalendarEvent): void {
    this.editingEvent.set(event);
    this.form = {
      title: event.title,
      description: event.description || '',
      startUtc: this.toDatetimeLocal(event.startUtc),
      endUtc: this.toDatetimeLocal(event.endUtc),
      location: event.location || '',
      attendeesCsv: ''
    };
    this.showModal.set(true);
  }

  closeModal(): void {
    this.showModal.set(false);
    this.editingEvent.set(null);
  }

  createEvent(): void {
    if (!this.form.title) return;
    this.subs.push(this.api.createEvent(this.form).subscribe(() => {
      this.closeModal();
      this.toast.success('Event created');
      this.loadEvents();
    }));
  }

  updateEvent(): void {
    const event = this.editingEvent();
    if (!event || !this.form.title) return;
    this.subs.push(this.api.updateEvent(event.id, this.form).subscribe(() => {
      this.closeModal();
      this.toast.success('Event updated');
      this.loadEvents();
    }));
  }

  deleteEvent(id: number): void {
    this.subs.push(this.api.deleteEvent(id).subscribe(() => {
      this.toast.success('Event deleted');
      this.loadEvents();
    }));
  }

  private toDatetimeLocal(utc: string): string {
    const d = new Date(utc);
    const pad = (n: number) => n.toString().padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }
}

// ai-agent-frontend/src/pages/Calendar.jsx
// src/pages/Calendar.jsx
import React, { useState, useEffect } from 'react';
import { Plus, Calendar as CalendarIcon, MapPin, Clock, MoreVertical } from 'lucide-react';
import { eventService } from '../services/api';

export default function Calendar() {
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showNewEvent, setShowNewEvent] = useState(false);
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [newEvent, setNewEvent] = useState({
    title: '',
    description: '',
    startUtc: '',
    endUtc: '',
    location: '',
    attendees: ''
  });

  useEffect(() => {
    loadEvents();
  }, []);

  const loadEvents = async () => {
    try {
      const today = new Date();
      const nextWeek = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000);
      
      const eventsData = await eventService.getAll(
        today.toISOString(),
        nextWeek.toISOString()
      );
      setEvents(eventsData);
    } catch (error) {
      console.error('Failed to load events:', error);
    } finally {
      setLoading(false);
    }
  };

  const createEvent = async (e) => {
    e.preventDefault();
    try {
      await eventService.create(newEvent);
      setShowNewEvent(false);
      setNewEvent({ 
        title: '', 
        description: '', 
        startUtc: '', 
        endUtc: '', 
        location: '',
        attendees: '' 
      });
      loadEvents();
    } catch (error) {
      console.error('Failed to create event:', error);
      alert('Failed to create event. Please try again.');
    }
  };

  const deleteEvent = async (eventId) => {
    if (window.confirm('Are you sure you want to delete this event?')) {
      try {
        await eventService.delete(eventId);
        loadEvents();
      } catch (error) {
        console.error('Failed to delete event:', error);
        alert('Failed to delete event.');
      }
    }
  };

  const formatEventTime = (startUtc, endUtc) => {
    const start = new Date(startUtc);
    const end = new Date(endUtc);
    
    const isSameDay = start.toDateString() === end.toDateString();
    
    if (isSameDay) {
      return {
        date: start.toLocaleDateString(),
        time: `${start.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} - ${end.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`
      };
    } else {
      return {
        date: `${start.toLocaleDateString()} - ${end.toLocaleDateString()}`,
        time: 'Multiple days'
      };
    }
  };

  const getUpcomingEvents = () => {
    const now = new Date();
    return events.filter(event => new Date(event.startUtc) >= now)
                .sort((a, b) => new Date(a.startUtc) - new Date(b.startUtc));
  };

  const getPastEvents = () => {
    const now = new Date();
    return events.filter(event => new Date(event.startUtc) < now)
                .sort((a, b) => new Date(b.startUtc) - new Date(a.startUtc));
  };

  const upcomingEvents = getUpcomingEvents();
  const pastEvents = getPastEvents();

  return (
    <div className="calendar-page">
      <div className="page-header">
        <div className="header-content">
          <h1>Calendar</h1>
          <p>Manage your events and schedule</p>
        </div>
        <button 
          className="btn btn-primary"
          onClick={() => setShowNewEvent(true)}
        >
          <Plus size={20} />
          New Event
        </button>
      </div>

      {/* New Event Modal */}
      {showNewEvent && (
        <div className="modal-overlay">
          <div className="modal">
            <h2>Create New Event</h2>
            <form onSubmit={createEvent}>
              <div className="form-group">
                <label>Title *</label>
                <input
                  type="text"
                  value={newEvent.title}
                  onChange={(e) => setNewEvent({ ...newEvent, title: e.target.value })}
                  required
                  placeholder="Meeting with team"
                />
              </div>
              <div className="form-group">
                <label>Description</label>
                <textarea
                  value={newEvent.description}
                  onChange={(e) => setNewEvent({ ...newEvent, description: e.target.value })}
                  rows="3"
                  placeholder="Brief description of the event..."
                />
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Start Time *</label>
                  <input
                    type="datetime-local"
                    value={newEvent.startUtc}
                    onChange={(e) => setNewEvent({ ...newEvent, startUtc: e.target.value })}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>End Time *</label>
                  <input
                    type="datetime-local"
                    value={newEvent.endUtc}
                    onChange={(e) => setNewEvent({ ...newEvent, endUtc: e.target.value })}
                    required
                  />
                </div>
              </div>
              <div className="form-group">
                <label>Location</label>
                <input
                  type="text"
                  value={newEvent.location}
                  onChange={(e) => setNewEvent({ ...newEvent, location: e.target.value })}
                  placeholder="Conference Room A"
                />
              </div>
              <div className="form-group">
                <label>Attendees</label>
                <input
                  type="text"
                  value={newEvent.attendees}
                  onChange={(e) => setNewEvent({ ...newEvent, attendees: e.target.value })}
                  placeholder="email1@example.com, email2@example.com"
                />
                <small>Separate multiple emails with commas</small>
              </div>
              <div className="modal-actions">
                <button 
                  type="button" 
                  className="btn btn-secondary"
                  onClick={() => setShowNewEvent(false)}
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary">
                  Create Event
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Events Lists */}
      <div className="calendar-content">
        {/* Upcoming Events */}
        <div className="events-section">
          <h2>Upcoming Events ({upcomingEvents.length})</h2>
          <div className="events-list">
            {loading ? (
              <div className="loading">Loading events...</div>
            ) : upcomingEvents.length === 0 ? (
              <div className="empty-state">
                <CalendarIcon size={48} />
                <p>No upcoming events</p>
                <button 
                  className="btn btn-primary"
                  onClick={() => setShowNewEvent(true)}
                >
                  Schedule Your First Event
                </button>
              </div>
            ) : (
              upcomingEvents.map(event => {
                const { date, time } = formatEventTime(event.startUtc, event.endUtc);
                return (
                  <div key={event.id} className="event-card">
                    <div className="event-time">
                      <div className="event-date">{date}</div>
                      <div className="event-time-display">
                        <Clock size={14} />
                        {time}
                      </div>
                    </div>
                    <div className="event-content">
                      <h3>{event.title}</h3>
                      {event.description && (
                        <p className="event-description">{event.description}</p>
                      )}
                      <div className="event-details">
                        {event.location && (
                          <div className="event-location">
                            <MapPin size={14} />
                            {event.location}
                          </div>
                        )}
                        {event.attendees && event.attendees.length > 0 && (
                          <div className="event-attendees">
                            Attendees: {event.attendees}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="event-actions">
                      <div className={`event-status ${event.status?.toLowerCase()}`}>
                        {event.status || 'Scheduled'}
                      </div>
                      <button 
                        className="icon-btn"
                        onClick={() => deleteEvent(event.id)}
                      >
                        <MoreVertical size={16} />
                      </button>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Past Events */}
        {pastEvents.length > 0 && (
          <div className="events-section">
            <h2>Past Events ({pastEvents.length})</h2>
            <div className="events-list">
              {pastEvents.map(event => {
                const { date, time } = formatEventTime(event.startUtc, event.endUtc);
                return (
                  <div key={event.id} className="event-card past">
                    <div className="event-time">
                      <div className="event-date">{date}</div>
                      <div className="event-time-display">{time}</div>
                    </div>
                    <div className="event-content">
                      <h3>{event.title}</h3>
                      {event.description && (
                        <p className="event-description">{event.description}</p>
                      )}
                      {event.location && (
                        <div className="event-location">
                          <MapPin size={14} />
                          {event.location}
                        </div>
                      )}
                    </div>
                    <div className="event-actions">
                      <div className="event-status completed">
                        Completed
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
