// ai-agent-frontend/src/app/features/tasks/tasks.component.ts
import { Component, OnInit, signal, computed, OnDestroy } from '@angular/core';
import { NgIf, NgFor, NgClass, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { TaskItem } from '../../core/models/models';
import { ToastService } from '../../shared/toast/toast.service';

@Component({
  selector: 'app-tasks',
  standalone: true,
  imports: [NgIf, NgFor, NgClass, DatePipe, FormsModule],
  template: `
    <div class="tasks-page">
      <div class="page-header">
        <div class="header-content">
          <h1>Tasks</h1>
          <p>Manage your tasks and to-dos</p>
        </div>
        <button class="btn btn-primary" (click)="showNewTask.set(true)">
          <span class="material-icons">add</span> New Task
        </button>
      </div>

      <div class="task-stats">
        <div class="stat-item"><div class="stat-number">{{ tasks().length }}</div><div class="stat-label">Total</div></div>
        <div class="stat-item"><div class="stat-number" style="color:#43e97b">{{ completedCount() }}</div><div class="stat-label">Done</div></div>
        <div class="stat-item"><div class="stat-number" style="color:#ffa726">{{ inProgressCount() }}</div><div class="stat-label">In Progress</div></div>
        <div class="stat-item"><div class="stat-number" style="color:#667eea">{{ todoCount() }}</div><div class="stat-label">To Do</div></div>
      </div>

      <div class="tasks-controls">
        <div class="search-box">
          <span class="material-icons">search</span>
          <input type="text" [(ngModel)]="search" placeholder="Search tasks..." />
        </div>
        <div class="filter-buttons">
          <button *ngFor="let s of statusFilters" class="filter-btn" [ngClass]="{'active': filter() === s}" (click)="filter.set(s); loadTasks()">{{ s }}</button>
        </div>
      </div>

      <div class="modal-overlay" *ngIf="showNewTask()" (click)="showNewTask.set(false)">
        <div class="modal" (click)="$event.stopPropagation()">
          <h2>Create New Task</h2>
          <form (ngSubmit)="createTask()">
            <div class="form-group"><label>Title *</label><input type="text" [(ngModel)]="newTask.title" name="title" required placeholder="What needs to be done?" /></div>
            <div class="form-group"><label>Description</label><textarea [(ngModel)]="newTask.description" name="desc" rows="3" placeholder="Add details..."></textarea></div>
            <div class="form-row">
              <div class="form-group"><label>Due Date</label><input type="datetime-local" [(ngModel)]="newTask.dueUtc" name="due" /></div>
              <div class="form-group"><label>Status</label>
                <select [(ngModel)]="newTask.status" name="status">
                  <option value="To Do">To Do</option>
                  <option value="In Progress">In Progress</option>
                  <option value="Done">Done</option>
                </select>
              </div>
            </div>
            <div class="modal-actions">
              <button type="button" class="btn btn-secondary" (click)="showNewTask.set(false)">Cancel</button>
              <button type="submit" class="btn btn-primary">Create Task</button>
            </div>
          </form>
        </div>
      </div>

      <div class="tasks-list">
        <div *ngIf="loading()" class="loading-state"><div class="spinner"></div><p>Loading tasks...</p></div>
        <div *ngIf="!loading() && filteredTasks().length === 0" class="empty-state">
          <p>{{ search ? 'No tasks match your search' : 'No tasks found' }}</p>
          <button *ngIf="!search" class="btn btn-primary" (click)="showNewTask.set(true)">Create Your First Task</button>
        </div>
        <div *ngFor="let task of filteredTasks()" class="task-card">
          <div class="task-main">
            <div class="task-checkbox">
              <input type="checkbox" [checked]="task.status === 'Done'" (change)="toggleTaskStatus(task.id, $event)" />
            </div>
            <div class="task-content">
              <h4 [ngClass]="{'completed': task.status === 'Done'}">{{ task.title }}</h4>
              <p *ngIf="task.description" class="task-description">{{ task.description }}</p>
              <div class="task-meta">
                <span *ngIf="task.dueUtc" class="due-date"><span class="material-icons" style="font-size:14px">calendar_today</span> Due: {{ task.dueUtc | date:'mediumDate' }}</span>
                <span class="status-badge" [class.to-do]="task.status === 'To Do'" [class.in-progress]="task.status === 'In Progress'" [class.done]="task.status === 'Done'">{{ task.status }}</span>
              </div>
            </div>
          </div>
          <div class="task-actions">
            <button class="icon-btn" (click)="deleteTask(task.id)" aria-label="Delete task"><span class="material-icons">delete</span></button>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrl: './tasks.component.scss'
})
export class TasksComponent implements OnInit, OnDestroy {
  tasks = signal<TaskItem[]>([]);
  filter = signal('all');
  search = '';
  loading = signal(true);
  showNewTask = signal(false);
  private subs: Subscription[] = [];

  statusFilters = ['all', 'To Do', 'In Progress', 'Done'];
  newTask = { title: '', description: '', dueUtc: '', status: 'To Do' };

  completedCount = computed(() => this.tasks().filter(t => t.status === 'Done').length);
  inProgressCount = computed(() => this.tasks().filter(t => t.status === 'In Progress').length);
  todoCount = computed(() => this.tasks().filter(t => t.status === 'To Do').length);

  filteredTasks = computed(() => {
    let list = this.filter() === 'all' ? this.tasks() : this.tasks().filter(t => t.status === this.filter());
    if (this.search) {
      const q = this.search.toLowerCase();
      list = list.filter(t => t.title.toLowerCase().includes(q) || t.description?.toLowerCase().includes(q));
    }
    return list;
  });

  constructor(
    private api: ApiService,
    private toast: ToastService
  ) {}

  ngOnInit(): void { this.loadTasks(); }
  ngOnDestroy(): void { this.subs.forEach(s => s.unsubscribe()); }

  loadTasks(): void {
    this.loading.set(true);
    const status = this.filter() === 'all' ? '' : this.filter();
    this.subs.push(this.api.getTasks(status).subscribe(tasks => {
      this.tasks.set(tasks);
      this.loading.set(false);
    }));
  }

  createTask(): void {
    if (!this.newTask.title) return;
    this.subs.push(this.api.createTask(this.newTask).subscribe(() => {
      this.showNewTask.set(false);
      this.newTask = { title: '', description: '', dueUtc: '', status: 'To Do' };
      this.toast.success('Task created');
      this.loadTasks();
    }));
  }

  toggleTaskStatus(id: number, event: any): void {
    const status = event.target.checked ? 'Done' : 'To Do';
    this.subs.push(this.api.updateTask(id, { status }).subscribe(() => this.loadTasks()));
  }

  deleteTask(id: number): void {
    this.subs.push(this.api.deleteTask(id).subscribe(() => {
      this.toast.success('Task deleted');
      this.loadTasks();
    }));
  }
}

// ai-agent-frontend/src/pages/Tasks.jsx
// src/pages/Tasks.jsx
import React, { useState, useEffect } from 'react';
import { Plus, Search, Filter, MoreVertical, Calendar, Flag } from 'lucide-react';
import { taskService } from '../services/api';

export default function Tasks() {
  const [tasks, setTasks] = useState([]);
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [showNewTask, setShowNewTask] = useState(false);
  const [newTask, setNewTask] = useState({
    title: '',
    description: '',
    dueUtc: '',
    status: 'To Do',
    priority: 'Medium'
  });

  useEffect(() => {
    loadTasks();
  }, [filter]);

  const loadTasks = async () => {
    try {
      const tasksData = await taskService.getAll(filter === 'all' ? '' : filter);
      setTasks(tasksData);
    } catch (error) {
      console.error('Failed to load tasks:', error);
    } finally {
      setLoading(false);
    }
  };

  const createTask = async (e) => {
    e.preventDefault();
    try {
      await taskService.create(newTask);
      setShowNewTask(false);
      setNewTask({ 
        title: '', 
        description: '', 
        dueUtc: '', 
        status: 'To Do',
        priority: 'Medium'
      });
      loadTasks();
    } catch (error) {
      console.error('Failed to create task:', error);
      alert('Failed to create task. Please try again.');
    }
  };

  const updateTaskStatus = async (taskId, newStatus) => {
    try {
      await taskService.update(taskId, { status: newStatus });
      loadTasks();
    } catch (error) {
      console.error('Failed to update task:', error);
      alert('Failed to update task status.');
    }
  };

  const deleteTask = async (taskId) => {
    if (window.confirm('Are you sure you want to delete this task?')) {
      try {
        await taskService.delete(taskId);
        loadTasks();
      } catch (error) {
        console.error('Failed to delete task:', error);
        alert('Failed to delete task.');
      }
    }
  };

  const getPriorityColor = (priority) => {
    switch (priority?.toLowerCase()) {
      case 'high': return '#f5576c';
      case 'medium': return '#ffa726';
      case 'low': return '#43e97b';
      default: return '#667eea';
    }
  };

  const filteredTasks = tasks.filter(task =>
    task.title.toLowerCase().includes(search.toLowerCase()) ||
    task.description?.toLowerCase().includes(search.toLowerCase())
  );

  const getTaskCounts = () => {
    const total = tasks.length;
    const completed = tasks.filter(t => t.status === 'Done').length;
    const inProgress = tasks.filter(t => t.status === 'In Progress').length;
    const todo = tasks.filter(t => t.status === 'To Do').length;
    
    return { total, completed, inProgress, todo };
  };

  const counts = getTaskCounts();

  return (
    <div className="tasks-page">
      <div className="page-header">
        <div className="header-content">
          <h1>Tasks</h1>
          <p>Manage your tasks and to-dos</p>
        </div>
        <button 
          className="btn btn-primary"
          onClick={() => setShowNewTask(true)}
        >
          <Plus size={20} />
          New Task
        </button>
      </div>

      {/* Task Statistics */}
      <div className="task-stats">
        <div className="stat-item">
          <div className="stat-number">{counts.total}</div>
          <div className="stat-label">Total</div>
        </div>
        <div className="stat-item">
          <div className="stat-number" style={{color: '#43e97b'}}>{counts.completed}</div>
          <div className="stat-label">Done</div>
        </div>
        <div className="stat-item">
          <div className="stat-number" style={{color: '#ffa726'}}>{counts.inProgress}</div>
          <div className="stat-label">In Progress</div>
        </div>
        <div className="stat-item">
          <div className="stat-number" style={{color: '#667eea'}}>{counts.todo}</div>
          <div className="stat-label">To Do</div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="tasks-controls">
        <div className="search-box">
          <Search size={20} />
          <input
            type="text"
            placeholder="Search tasks..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="filter-buttons">
          {['all', 'To Do', 'In Progress', 'Done'].map(status => (
            <button
              key={status}
              className={`filter-btn ${filter === status ? 'active' : ''}`}
              onClick={() => setFilter(status)}
            >
              {status}
            </button>
          ))}
        </div>
      </div>

      {/* New Task Modal */}
      {showNewTask && (
        <div className="modal-overlay">
          <div className="modal">
            <h2>Create New Task</h2>
            <form onSubmit={createTask}>
              <div className="form-group">
                <label>Title *</label>
                <input
                  type="text"
                  value={newTask.title}
                  onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                  required
                  placeholder="What needs to be done?"
                />
              </div>
              <div className="form-group">
                <label>Description</label>
                <textarea
                  value={newTask.description}
                  onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                  rows="3"
                  placeholder="Add details about the task..."
                />
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Due Date</label>
                  <input
                    type="datetime-local"
                    value={newTask.dueUtc}
                    onChange={(e) => setNewTask({ ...newTask, dueUtc: e.target.value })}
                  />
                </div>
                <div className="form-group">
                  <label>Priority</label>
                  <select
                    value={newTask.priority}
                    onChange={(e) => setNewTask({ ...newTask, priority: e.target.value })}
                  >
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                  </select>
                </div>
              </div>
              <div className="form-group">
                <label>Status</label>
                <select
                  value={newTask.status}
                  onChange={(e) => setNewTask({ ...newTask, status: e.target.value })}
                >
                  <option value="To Do">To Do</option>
                  <option value="In Progress">In Progress</option>
                  <option value="Done">Done</option>
                </select>
              </div>
              <div className="modal-actions">
                <button 
                  type="button" 
                  className="btn btn-secondary"
                  onClick={() => setShowNewTask(false)}
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary">
                  Create Task
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Tasks List */}
      <div className="tasks-list">
        {loading ? (
          <div className="loading">Loading tasks...</div>
        ) : filteredTasks.length === 0 ? (
          <div className="empty-state">
            <p>{search ? 'No tasks match your search' : 'No tasks found'}</p>
            {!search && (
              <button 
                className="btn btn-primary"
                onClick={() => setShowNewTask(true)}
              >
                Create Your First Task
              </button>
            )}
          </div>
        ) : (
          filteredTasks.map(task => (
            <div key={task.id} className="task-card">
              <div className="task-main">
                <div className="task-checkbox">
                  <input
                    type="checkbox"
                    checked={task.status === 'Done'}
                    onChange={(e) => updateTaskStatus(
                      task.id, 
                      e.target.checked ? 'Done' : 'To Do'
                    )}
                  />
                </div>
                <div className="task-content">
                  <h4 className={task.status === 'Done' ? 'completed' : ''}>
                    {task.title}
                  </h4>
                  {task.description && (
                    <p className="task-description">{task.description}</p>
                  )}
                  <div className="task-meta">
                    {task.dueUtc && (
                      <span className="due-date">
                        <Calendar size={14} />
                        Due: {new Date(task.dueUtc).toLocaleDateString()}
                      </span>
                    )}
                    <span 
                      className="priority-badge"
                      style={{ backgroundColor: getPriorityColor(task.priority) }}
                    >
                      <Flag size={12} />
                      {task.priority || 'Medium'}
                    </span>
                    <span className={`status-badge ${task.status.toLowerCase().replace(' ', '-')}`}>
                      {task.status}
                    </span>
                  </div>
                </div>
              </div>
              <div className="task-actions">
                <button 
                  className="icon-btn"
                  onClick={() => deleteTask(task.id)}
                >
                  <MoreVertical size={16} />
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
